# This file was generated by GoReleaser. DO NOT EDIT.
class Smock < Formula
  desc ""
  homepage ""
  version "0.1.5"

  if OS.mac?
    url "https://github.com/broothie/smock/releases/download/v0.1.5/smock_0.1.5_darwin_amd64.tar.gz"
    sha256 "7432b722e835f220855d75ec3ebebb9a7fa6024143f1f8e289538ddb841f62c7"
  elsif OS.linux?
    url "https://github.com/broothie/smock/releases/download/v0.1.5/smock_0.1.5_linux_amd64.tar.gz"
    sha256 "324747ec95656a0aa1ced1c2e6bd4725ac42638925ada0f0638b7e1a838cd235"
  end

  def install
    bin.install "smock"
  end
end
